theme: minima
title: Era's blog
name: "Era Choshen's Blog"
author: Era Choshen
description: Very occasional blogs

# Build settings
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  toc_levels: 1..4
